version: "3"
services:

  specs:
    image: specs
    ports:
      - "10000:8080"
    networks:
      - backend
    depends_on:
      - db
  db:
    image: postgres:9.4
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:

volumes:
  db-data: